language: ruby

rvm:
  - 2.5
  - 2.6
  - 2.7
  - ruby-head

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

cache:
  - bundler

gemfile:
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile
  - gemfiles/5.2.gemfile
  - gemfiles/6.0.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head

