name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3.3', '3.2', '3.1', '3.0', '2.7', '2.6']
        gemfile: ['8.0', '7.2', '7.1', '7.0', '6.1', '6.0']
        exclude:
          # rails 8.0: support ruby 3.2+
          - gemfile: '8.0'
            ruby-version: '3.1'
          - gemfile: '8.0'
            ruby-version: '3.0'
          - gemfile: '8.0'
            ruby-version: '2.7'
          - gemfile: '8.0'
            ruby-version: '2.6'
          # rails 7.2: support ruby 3.1+
          - gemfile: '7.2'
            ruby-version: '3.0'
          - gemfile: '7.2'
            ruby-version: '2.7'
          - gemfile: '7.2'
            ruby-version: '2.6'
          # rails 7.1/7.0: support ruby 2.7+
          - gemfile: '7.1'
            ruby-version: '2.6'
          - gemfile: '7.0'
            ruby-version: '2.6'
    runs-on: ubuntu-latest
    name: rails ${{ matrix.gemfile }}, ruby ${{ matrix.ruby-version }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: false
      - name: Bundle install
        run: |
          bundle config set gemfile "${GITHUB_WORKSPACE}/gemfiles/${{ matrix.gemfile }}.gemfile"
          bundle install --jobs 4 --retry 3
      - name: Run tests
        run: bundle exec rake test
