name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        ruby-version:
          - "2.6"
          - "2.7"
          - "3.0"
          - "3.1"
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # 'bundle install' and cache gems
      - name: Run tests
        run: bundle exec rake
        env:
          BUNDLE_GEMFILE: gemfiles/6.0.gemfile

# gemfile:
#   - gemfiles/5.0.gemfile
#   - gemfiles/5.1.gemfile
#   - gemfiles/5.2.gemfile
#   - gemfiles/6.0.gemfile
