name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - gemfile: "6.0"
            ruby-version: "2.6"
          - gemfile: "6.0"
            ruby-version: "2.7"
          - gemfile: "6.0"
            ruby-version: "3.0"
          - gemfile: "6.0"
            ruby-version: "3.1"
    runs-on: ubuntu-latest
    name: rails ${{ matrix.gemfile }}, ruby ${{ matrix.ruby-version }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: false
      - name: Bundle install
        run: |
          bundle config set gemfile "${GITHUB_WORKSPACE}/gemfiles/${{ matrix.gemfile }}.gemfile"
          bundle install --jobs 4 --retry 3
      - name: Run tests
        run: bundle exec rake test
